# ----------------------------------------------------------------------------
#
# Package             : marathon-client
# Source Repo         : https://github.com/willroden/marathon-client
# Travis Job Link     : https://travis-ci.com/github/santosh653/marathon-client
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
  - amd64
  - ppc64le
language: java
jdk:
  - oraclejdk11
  - openjdk11
# Excluding oraclejdk11 on power as it is not supported.
jobs:
 exclude:
  - oraclejdk11
    arch: ppc64le

